title: Anup Kolhe 
logo: /assests/Profile_image
description: Hello! I'm Anup, passionate about data science, and I come from a background in Mechanical Engineering and Supply Chain Analysis. Currently, I'm fully immersed in exploring the intricacies of data science.

theme: jekyll-theme-minimal 
